#!/bin/sh

##
## BSPWM appearance
##

## Borders
bspc config border_width 2
bspc config window_gap 2
bspc config borderless_monocle true
bspc config gapless_monocle true

## Colour scheme
black='#000000'
blue='#268bd2'
cyan='#2aa198'
green='#859900'
magenta='#d33682'
orange='#cb4b16'
red='#dc322f'
violet='#6c71c4'
white='#D0D0D0'
yellow='#b58900'

## Regular border colours
bspc config focused_border_color $magenta
bspc config active_border_color $magenta
bspc config normal_border_color $blue
bspc config presel_border_color $yellow
bspc config urgent_border_color $red

## Locked border colours
bspc config focused_locked_border_color $black
bspc config active_locked_border_color $black
bspc config normal_locked_border_color $black

## Sticky border colours
bspc config focused_sticky_border_color $green
bspc config active_sticky_border_color $green
bspc config normal_sticky_border_color $green  

## Private border colours
bspc config focused_private_border_color $white
bspc config active_private_border_color $white
bspc config normal_private_border_color $white

##
## BSPWM behaviour
##

## General configuration
bspc config focus_follows_pointer true
bspc config auto_cancel true
bspc config split_ratio 0.50
bspc config auto_alternate false

## Rules
bspc rule -a Steam floating=on

## Desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

## Panel
${HOME}/.bspwm/launch-panel.sh

## EOF
