#!/bin/sh

# Appearance

. ${HOME}/.bspwm/colors

white="#${white}"
black="#${black}"

red="#${red}"
orange="#${orange}"
yellow="#${yellow}"
green="#${green}"
cyan="#${cyan}"
blue="#${blue}"
violet="#${violet}"
magenta="#${magenta}"

bspc config focused_border_color    ${magenta}
bspc config active_border_color     ${magenta}
bspc config normal_border_color     ${blue}
bspc config presel_border_color     ${yellow}
bspc config urgent_border_color     ${red}

bspc config border_width        2
bspc config window_gap          8
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Behaviour

bspc config auto_cancel             true
bspc config split_ratio             0.50
bspc config auto_alternate          false
bspc config focus_follows_pointer   false

# Rules

bspc rule -a    Steam floating=on

# Monitors

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Keybinding daemon

SXHKD_SHELL=/bin/sh sxhkd -c ${HOME}/.bspwm/sxhkdrc &

# Panel

${HOME}/.bspwm/panel.sh 2> /dev/null &

## EOF
