#!/bin/sh
# vim: set nowrap:

PANEL_FONT='xft:DejaVu Sans Mono:bold:size=11'
PANEL_HEIGHT=20

. ${HOME}/.bspwm/colors

white="#FF${white}"
black="#FF${black}"

red="#FF${red}"
orange="#FF${orange}"
yellow="#FF${yellow}"
green="#FF${green}"
cyan="#FF${cyan}"
blue="#FF${blue}"
violet="#FF${violet}"
magenta="#FF${magenta}"

## EOF
