#!/bin/sh
# vim: set nowrap:

PANEL_FONT='-xos4-terminus-medium-*-*-*-14-*-*-*-*-*-iso10646-*'
PANEL_HEIGHT=18

. ${HOME}/.bspwm/colors

white="#FF${white}"
black="#FF${black}"

red="#FF${red}"
orange="#FF${orange}"
yellow="#FF${yellow}"
green="#FF${green}"
cyan="#FF${cyan}"
blue="#FF${blue}"
violet="#FF${violet}"
magenta="#FF${magenta}"

## EOF
