#!/bin/sh

## Panel settings

PANEL_FIFO='/tmp/bspwm-panel-fifo'
PANEL_FONT_FAMILY='xft:DejaVu Sans Mono:bold:size=11'
PANEL_HEIGHT=18
PANEL_HIDDEN_FLAG='/tmp/bspwm-panel-hidden'

## BSPWM settings

WINDOW_GAP=8

## Solarized colours

black='000000'
white='FFFFFF'

red='dc322f'
orange='cb4b16'
yellow='b58900'
green='859900'
cyan='2aa198'
blue='268bd2'
magenta='d33682'
violet='6c71c4'

dark0='002b36'
dark1='073642'

foreground0='586e75'
foreground1='657b83'
foreground2='839496'
foreground3='93a1a1'

light0='eee8d5'
light1='fdf6e3'

## dmenu settings

bspwm_dmenu()
{
    dmenu_run -i                      \
    -h ${PANEL_HEIGHT}                \
    -fn "\'$PANEL_FONT_FAMILY\'"      \
    -nf "#$foreground3" -nb "#$black" \
    -sf "#$black"       -sb "#$blue"  \
    ;
}

