#!/bin/sh

## Panel variables
PANEL_FONT='Gohufont'
PANEL_HEIGHT=16
PANEL_FIFO='/tmp/bspwm/panel-fifo'
PANEL_HIDDEN_FLAG='/tmp/bspwm/panel-hidden'
BATTERY_LOC='NONE' # BATTERY='NONE' to disable bat. monitor
BATTERY_NOW="${BATTERY_LOC}/current"                         
BATTERY_FULL="${BATTERY_LOC}/full"                         
BATTERY_STATUS="${BATTERY_LOC}/status"                         

## BSPWM variables
BORDER_WIDTH=1
WINDOW_GAP=1
BSPWM_INITIALIZED_FLAG='/tmp/bspwm/initialized'

## Colour scheme
foreground='93a1a1'
background='000000'
black='000000'
blue='268bd2'
cyan='2aa198'
green='859900'
magenta='d33682'
orange='cb4b16'
red='dc322f'
violet='6c71c4'
white='B0B0B0'
yellow='b58900'

## Get set up
mkdir /tmp/bspwm/ 2> /dev/null

## Toggle panel visibility
panel_toggle()
{
    if [ -e $PANEL_HIDDEN_FLAG ]
    then
        xdotool search --name '_bspwmpanelbar_' windowmap
        bspc config top_padding $PANEL_HEIGHT
        rm -f $PANEL_HIDDEN_FLAG
    else
        xdotool search --name '_bspwmpanelbar_' windowunmap
        bspc config top_padding 0
        touch $PANEL_HIDDEN_FLAG
    fi;
}

## Modified version of suckless' dmenu_run (requires dmenu2)
panel_dmenu()
{
    [ -e $PANEL_HIDDEN_FLAG ] && bspc config top_padding $PANEL_HEIGHT

    CACHE="${XDG_CACHE_HOME:-"${HOME}/.cache"}/dmenu_run"
    IFS=:
    stest -dqr -n $CACHE $PATH && stest -flx $PATH | sort -u > $CACHE

    DMENU_CMD="$(                                           \
        dmenu -i -h ${PANEL_HEIGHT} -fn "${PANEL_FONT}"     \
        -nf "#$foreground" -nb "#$background"               \
        -sf "#$blue"       -sb "#$background"               \
        < ${CACHE}                                          \
    )"
    eval $DMENU_CMD &

    [ -e $PANEL_HIDDEN_FLAG ] && bspc config top_padding 0;
}

## Safely kill bspwm
bspwm_quit()
{
    rm -Rf /tmp/bspwm/

    for ARG in bspwm-panel xtitle bspc 
    do
        while pgrep -x $ARG > /dev/null 2>&1
        do
            pkill -x -9 $ARG 2> /dev/null
        done
    done
    bspc quit;
}

## EOF #################################################################
