#!/bin/sh

## Panel variables #####################################################

PANEL_FIFO='/tmp/bspwm-panel-fifo'
PANEL_FONT_FAMILY='xft:DejaVu Sans Mono:bold:size=11'
PANEL_HEIGHT=18
#BAT='/sys/class/power_supply/BAT1'
BAT='NONE' # BAT='NONE' to disable bat. monitor; BAT='AC' to show "A/C"

## BSPWM variables #####################################################

BORDER_WIDTH=1
WINDOW_GAP=1
PANEL_HIDDEN_FLAG='/tmp/bspwm-panel-hidden'
BSPWM_INITIALIZED_FLAG='/tmp/bspwm-initialized'

## Colour scheme #######################################################

black='000000'
white='B0B0B0'
red='dc322f'
orange='cb4b16'
yellow='b58900'
green='859900'
cyan='2aa198'
blue='268bd2'
magenta='d33682'
violet='6c71c4'
foreground0='586e75'
foreground1='657b83'
foreground2='839496'
foreground3='93a1a1'
dark0='002b36'
dark1='073642'
light0='eee8d5'
light1='fdf6e3'

## dmenu ###############################################################

bspwm_dmenu_run()
{
    # Top padding if needed
    [ -e $PANEL_HIDDEN_FLAG ] && bspc config top_padding $PANEL_HEIGHT
   
    # Parse $PATH, check for changes to cache 
    CACHE=${XDG_CACHE_HOME:-"${HOME}/.cache"}/dmenu_run
    IFS=:
    stest -dqr -n $CACHE $PATH && stest -flx $PATH | sort -u > $CACHE
    
    # Use dmenu (requires dmenu2) to pick an option from the cache
    dmenu -i -h ${PANEL_HEIGHT} -fn "\'$PANEL_FONT_FAMILY\'"           \
          -nf "#$foreground3" -nb "#$black" -sf "#$black" -sb "#$blue" \
        < $CACHE
   
    # Remove top padding  if needed
    [ -e $PANEL_HIDDEN_FLAG ] && bspc config top_padding 0;
}

## Show/hide panel #####################################################

bspwm_panel_toggle()
{
    if [ -f ${PANEL_HIDDEN_FLAG} ]
    then
        rm -f ${PANEL_HIDDEN_FLAG}
        xdotool search --name 'bspwmpanelbar' windowmap
        bspc config top_padding $PANEL_HEIGHT
    else
        touch ${PANEL_HIDDEN_FLAG}
        xdotool search --name 'bspwmpanelbar' windowunmap
        bspc config top_padding 0
    fi;
}

## BSPWM quit script ###################################################

bspwm_quit()
{
    rm -f $PANEL_HIDDEN_FLAG
    rm -f $BSPWM_INITIALIZED_FLAG

    while pgrep -x bspwm-panel > /dev/null 2>&1
    do
        pkill -x -9 bspwm-panel 2> /dev/null
    done

    while pgrep -x redshift > /dev/null 2>&1
    do
        pkill -x -9 redshift 2> /dev/null
    done

    bspc quit;
}

## EOF #################################################################
