#!/bin/sh

## X settings
test -e ${HOME}/.xmodmap && xmodmap ${HOME}/.xmodmap
xset -b s 1800 dpms 1800 1800 1800
xrdb -load ${HOME}/.Xresources
feh --bg-max --no-fehbg ${HOME}/.config/openbox/wallpaper.jpg

## External applications
mpc status || mpd &

## Dock
pgrep tint2 || tint2 -c ${HOME}/.config/openbox/tint2rc &

## EOF

