(load "~/quicklisp.lisp")
(quicklisp-quickstart:install :path "~/.quicklisp")
(require 'ql)
(ql:add-to-init-file)
(ql:quickload 'clx)
(ql:quickload 'cl-ppcre)
(ql:quickload 'swank)
(ql:quickload 'xembed)
(ql:quickload 'zpng)
(exit)
