#!/bin/sh

# X settings
[ -e ${HOME}/.xmodmap ] && xmodmap ${HOME}/.xmodmap
xset -b s 1800 dpms 1800 1800 1800
xrdb -load ~/.Xresources

# Make QT pick up on GTK themes and icons
export DESKTOP_SESSION=gnome

exec fluxbox
